### ISSUE TITLE
Do you have testing mocks?

### ISSUE THREAD

**Issue by ysyyork** [spreedly/spreedly-gem#68]
Hi, is there an easy way to mock spreedly env for unit testing?

**Comment by robcole** [comment]
@ysyyork - This is a few months late, but might be helpful for others.

What we're doing is using `Webmock` to stub out the XML request & response bodies. I built out the XML by walking through various actions we needed to hit in Development mode and setting ENV['SHOW_RAW_RESPONSE'] to true as an environment variable: this dumps the XML that is being received to your screen.

We then use Webmock to mock the responses and build new Spreedly objects from the XML dumped from that. In at least one case, we use that XML to build up a new Spreedly Transaction, like this:

```
# stub_spreedly_charge mocks the file and returns XML for the transaction type
xml = stub_spreedly_charge(payment, :charge_success)
transaction = Spreedly::Transaction.new_from(Nokogiri::XML(xml))

# rest of this is specific to our test, but ensuring that we store JSON properly from the 
# spreedly request object
json = transaction.to_json
expected_hash = JSON.parse(json)
expect{payment.process_payment}
  .to change{payment.response_hash}
  .from({})
  .to(expected_hash)
```

This example might be too domain specific, but thought it might be helpful to you/others.
