### ISSUE TITLE
Don't raise exceptions for missing fields

### ISSUE THREAD

**Issue by rwdaigle** [spreedly/spreedly-gem#69]
When an API response does not have the expected fields, a parsing exception will result which makes it seem like the tx failed when in actuality it succeeded. We shouldn't fail parsing for missing fields, or should fail in a very predictable explicit fashion (like throw a clearly client-side exception).

/cc @spreedly/product-dev

**Comment by jknipp** [comment]
Details on the incident at https://spreedly.zendesk.com/agent/tickets/17288

When a field is missing the Spreedly Gem throws the following error:

```
NoMethodError: undefined method `inner_html' for nil:NilClass
```
