### ISSUE TITLE
Callback url can't be blank Redirect url can't be blank

### ISSUE THREAD

**Issue by devmtnaing** [spreedly/spreedly-gem#72]
Hi

response = env.purchase_on_gateway(gateway_token, payment_token, 33)

just calling the purchase_on_gateway method as it mentioned in the readme file, but it  says callback url can't be blank. gatway is :test and payment_method_type is sprel. 

I tried env.purchase_on_gateway(gateway_token, payment_token, 33, redirect_url: r_url, callback_url: c_url)

still doesn't seem to be working. What am I doing wrong? Thanks

**Comment by davidsantoso** [comment]
@devmtnaing can you give the `gateway_token` and `payment_token` you are using?

**Comment by devmtnaing** [comment]
@davidsantoso gateway_token = 'SJs1ZlZE4CvqNk08JvqdOyUPHdr' and payment_token = 'HpkEY383qbB5jxmfR1CLpM3bbU6'. 

mainly trying to figure out paypal and offsite payments. thanks

**Comment by davidsantoso** [comment]
@devmtnaing I apologize- at this point the gem isn't fully supporting offsite transactions so the `redirect_url` and `callback_url` options aren't even making it to the gateway.

See https://github.com/spreedly/spreedly-gem/blob/master/lib/spreedly/environment.rb#L281

I'm adding support and have it working on an `offsite-support` branch. Hoping to merge it in to `master` tomorrow and get RubyGems updated. Stay tuned.

https://github.com/spreedly/spreedly-gem/commit/7c671d623ad3941f372e807a026a9c1689bd8dc9

**Comment by devmtnaing** [comment]
Ahh I see. 

merge would be an ideal and great help. Thanks @davidsantoso

**Comment by davidsantoso** [comment]
@devmtnaing merged and updated on RubyGems.
